version: "3.9"

services:
  development:
    build: .
    ports:
      - "8080:8080"
      - "3000:3000"
    volumes:
      - mern_code:/code
    command: tail -f /dev/null

volumes:
  mern_code:
    external: true